name: C/C++ CI with Singularity

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup runc wget
        sudo wget https://github.com/hpcng/singularity/releases/download/v3.8.5/singularity-ce_3.8.5_amd64.deb
        sudo dpkg -i singularity-ce_3.8.5_amd64.deb

    - name: Build the application
      run: make

    - name: Create Singularity Definition File
      run: |
        echo "Bootstrap: docker" > Singularity.def
        echo "From: ubuntu:20.04" >> Singularity.def
        echo "%post" >> Singularity.def
        echo "    apt-get update && apt-get install -y build-essential" >> Singularity.def
        echo "    make" >> Singularity.def
        echo "%runscript" >> Singularity.def
        echo "    exec ./hello" >> Singularity.def

    - name: Build Singularity Image
      run: singularity build cicd.sif Singularity.def

    - name: Create Dockerfile for SIF Image
      run: |
        echo "FROM alpine:latest" > Dockerfile
        echo "RUN apk --no-cache add singularity" >> Dockerfile
        echo "COPY cicd.sif /usr/local/bin/cicd.sif" >> Dockerfile
        echo 'ENTRYPOINT ["singularity", "exec", "/usr/local/bin/cicd.sif"]' >> Dockerfile
        echo 'CMD ["./hello"]' >> Dockerfile

    - name: Build Docker Image
      run: docker build -t rambajgire/cicd:singularity .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push rambajgire/cicd:singularity

    - name: Clean up
      run: make clean
