name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: make
      run: make
    - name: make run
      run: make run
    - name: make clean
      run : make clean
  testing:
    runs-on: ubuntu-latest
    needs: build
    name: test environment

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: make
      run: make
    - name: running test cases
      run: chmod +x ./test.sh 
            ./test.sh
    - name: make clean
      run : make clean
    
    Deploying:
    runs-on: ubuntu-latest
    needs: testing
    name: prod environment

    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: make
      run: make
    - name : build and push on docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
      image: rambajgire/cicd
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }} 
      password: ${{ secrets.DOCKER_PASSWORD }}
            
